version: '2'

services:
  jupyter:
    image: mnagaku/lc-minimal-notebook
    ports:
      - "8888:8888"
    command: bash -c "git clone --depth 1 https://github.com/mnagaku/docker-handson.git ; set +u ; . /usr/local/bin/start.sh jupyter notebook --NotebookApp.token=''"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
