version: '3.7'

services:
  jupyter:
    image: mnagaku/lc-minimal-notebook
    ports:
      - "8888:8888"
    command: bash -c "git clone --depth 1 https://github.com/mnagaku/docker-handson.git ; set +u ; . /usr/local/bin/start.sh jupyter notebook --NotebookApp.token=''"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  adminer:
    image: adminer
    ports:
      - 8080:8080
  mariadb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: example

